
server:
  port: 18005



spring:
  application:
    name: nacos-demo
  cloud:
    nacos:
      discovery:
        server-addr: 121.36.11.25:8848 # 配置nacos地址
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.36.11.25:12345/server_cloud?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    password: hd@12345
    username: root


  #采用nacos 注册中心 先忽略掉eureka 注册中心
  autoconfigure:
    exclude: org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration


#暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'